### ISSUE TITLE
something go wrong

### ISSUE THREAD

**Issue by vichHuang** [axetroy/sms-boom#10]
```bash
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Keyboard.type (E:\Node\短信轰炸\sms-boom\node_modules\puppeteer\lib\Input.js:106:24)
    at ElementHandle.type (E:\Node\短信轰炸\sms-boom\node_modules\puppeteer\lib\ElementHandle.js:106:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
SIGINT received
```

**Comment by axetroy** [comment]
@vichHuang 

能够给详细点的信息。
是按照哪个步骤运行的？

**Comment by vichHuang** [comment]
E:\Node\短信轰炸\sms-boom>node ./example/once.js
process 6312 start.
>>>>>
打开浏览器...
进入到 http://www.surong360.com/SR360/application/user/emailRegisterPage.do
> undefined { delay: 100 }
[Fail]: 速融
something go wrong
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Keyboard.type (E:\Node\短信轰炸\sms-boom\node_modules\puppeteer\lib\Input.js:106:24)
    at ElementHandle.type (E:\Node\短信轰炸\sms-boom\node_modules\puppeteer\lib\ElementHandle.js:106:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
SIGINT received
process 6312 exit.
这是全部信息了

从码源运行的

**Comment by axetroy** [comment]
@vichHuang 
你没有设置环境变量

```bash
export PHONE=13800000000
```

**Comment by vichHuang** [comment]
谢谢大佬解答
