### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by chunjispring** [axetroy/sms-boom#17]
/usr/local/lib/node_modules/smsboomer/index.js:46
  app.init(async () => {
                 ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/smsboomer/bin/boomer:4:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

安装没有问题，执行命令时报上述错误。ubuntu17.10系统
xx@ubuntu:~$ uname -a
Linux ubuntu 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

xx@ubuntu:~$ nodejs -v
v6.11.4

**Comment by axetroy** [comment]
NodeJs 需要更高的版本，详情看Readme有标识。

理论上，需要7.6.0以上

**Comment by chunjispring** [comment]
ok，晓得了，ubuntu默认给装的nodejs太低，那我回去装个高版本的试试。
