### ISSUE TITLE
npm安装后出现报错...求大神

### ISSUE THREAD

**Issue by chenyyyang** [axetroy/sms-boom#35]
module.js:538
    throw err;
    ^

Error: Cannot find module 'caporal'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\xxx\nodejs_learn\sms-boom-master\bin\smsboomer:2:17)
 at Module._compile (module.js:635:30)
 at Object.Module._extensions..js (module.js:646:10)
 at Module.load (module.js:554:32)
 at tryModuleLoad (module.js:497:12)
 at Function.Module._load (module.js:489:3)

**Comment by chenyyyang** [comment]
module.js:538
    throw err;
    ^

Error: Cannot find module 'faker'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\吴晨炀\nodejs_learn\sms-boom-master\index.js:4:15)
 at Module._compile (module.js:635:30)
 at Object.Module._extensions..js (module.js:646:10)
 at Module.load (module.js:554:32)
 at tryModuleLoad (module.js:497:12)
 at Function.Module._load (module.js:489:3)
 at Module.require (module.js:579:17)
 at require (internal/module.js:11:18)
 at Object.<anonymous> (C:\Users\吴晨炀\nodejs_learn\sms-boom-master\bin\smsboomer:4:16)                                       at
 Module._compile (module.js:635:30)                                                                                         at
 Object.Module._extensions..js (module.js:646:10)                                                                           at
 Module.load (module.js:554:32)

**Comment by 1eozhang** [comment]
没学过NODE.JS。 运行的介绍能否再详细点

**Comment by axetroy** [comment]
@1eozhang 
1. 首先安装nodejs，看官网
2. 运行npm命令

**Comment by 1eozhang** [comment]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1  
这句在哪敲呢？

**Comment by 1eozhang** [comment]
@axetroy 
![image](https://user-images.githubusercontent.com/23225983/34244671-5e5822fa-e661-11e7-8231-4a9ab0f5b75b.png)

**Comment by 1eozhang** [comment]
@axetroy 


![1513841334 1](https://user-images.githubusercontent.com/23225983/34245198-d411a85c-e663-11e7-8845-448349a440fd.jpg)

**Comment by chenyyyang** [comment]
应该是windows下面没有 headless 浏览器吧

**Comment by axetroy** [comment]
@chenyyyang 
WIndows的电脑是可以的, 亲测, chromium是自动下载的, 不管你是在哪个平台

**Comment by zhangyuanliang** [comment]
@1eozhang 报错解决了吗？我的也是报这个错
