### ISSUE TITLE
运行报错呢，什么原因？

### ISSUE THREAD

**Issue by zhangyuanliang** [axetroy/sms-boom#40]
$ smsboomer 1519xxxxxx
[524]: start.
Downloading Chromium...
Boomer init fail...
{ TimeoutError: Promise timed out after 10000 milliseconds
    at Timeout.setTimeout [as _onTimeout] (D:\software\node\node_modules\smsboomer\node_modules\p-timeout\index.js:27:54)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5) name: 'TimeoutError' }
[524]: Exit with code 1.

**Comment by axetroy** [comment]
这个是下载超时的问题，已经把下载超时的时间延长
