### ISSUE TITLE
启动chrome失败

### ISSUE THREAD

**Issue by WongCM** [axetroy/sms-boom#42]
```
[13044]: start.
Error: Failed to launch chrome!
/usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:211:14)
    at Interface.helper.addEventListener (/usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:200:50)
    at Interface.emit (events.js:164:20)
    at Interface.close (readline.js:381:8)
    at Socket.onend (readline.js:154:10)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[13044]: Exit with code 0.
```

**Comment by WongCM** [comment]
然后运行了这一串

```
yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y
```

但是当中提示

```
No package gtk3.x86_64 available.
```

然后进入到Chrome文件夹
```
cd /usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/
```

运行
```
ldd chrome | grep not
```

提示
```
ldd chrome | grep not
./chrome: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./chrome)
	libatk-bridge-2.0.so.0 => not found
	libgtk-3.so.0 => not found
	libgdk-3.so.0 => not found
```

运行smsboomer也是报错
```
[28782]: start.
Error: Failed to launch chrome!
/usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:211:14)
    at Interface.helper.addEventListener (/usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:200:50)
    at Interface.emit (events.js:164:20)
    at Interface.close (readline.js:381:8)
    at Socket.onend (readline.js:154:10)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[28782]: Exit with code 0.
```

安装不了这些个东西。。。
```
[root@host chrome-linux]# sudo yum install gtk3.x86_64
已加载插件：fastestmirror
设置安装进程
Loading mirror speeds from cached hostfile
 * base: mirrors.oit.uci.edu
 * elrepo-kernel: repos.lax-noc.com
 * extras: repos.lax.quadranet.com
 * updates: centos-distro.1gservers.com
 * webtatic: us-east.repo.webtatic.com
No package gtk3.x86_64 available.
错误：无须任何处理

```

**Comment by Jrexexe** [comment]
同样的问题啊，而且是macbook
