### ISSUE TITLE
这是啥问题啊====改了半天也不行啊

### ISSUE THREAD

**Issue by nodiexiaoqiang** [axetroy/sms-boom#45]
/usr/local/lib/node_modules/smsboomer/index.js:48
  app.init(async () => {
                 ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/smsboomer/bin/smsboomer:4:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by hyj1991** [comment]
感觉是你的 node 版本不支持 async 语法，使用 > node-v7.5.0 的版本试下

**Comment by harryyuanfeng** [comment]
遇到同样的问题，升级node就可以
