### ISSUE TITLE
在ubuntu 16.04 跑出现的错误

### ISSUE THREAD

**Issue by harryyuanfeng** [axetroy/sms-boom#49]
```
[13768]: start.
Error: Failed to launch chrome!
/usr/lib/node_modules/smsboomer/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:211:14)
    at Interface.helper.addEventListener (/usr/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:200:50)
    at Interface.emit (events.js:185:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[13768]: Exit with code 0.

```

一般怎么样处理这个问题？

**Comment by harryyuanfeng** [comment]
根据这个好像修复了问题。https://github.com/astefanutti/decktape/issues/126

但是出现新的错误：

```
[16544]: start.
Error: Failed to launch chrome!
[0315/142956.003146:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:211:14)
    at Interface.helper.addEventListener (/usr/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:200:50)
    at Interface.emit (events.js:185:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[16544]: Exit with code 0.

```

**Comment by WindomZ** [comment]
Running as root without --no-sandbox

在Ubuntu16.04下正常，可以在非root下运行

**Comment by sakuyamaij** [comment]
@harryyuanfeng 
我也是这个问题，加了行代码后解决了
https://github.com/sakuyamaij/sms-boom/commit/79e2de8449fe1b079ccf63dc7c8cee7f9b53abc9

**Comment by hebaoying** [comment]
你好，请问怎样在 ubuntu 上安装。。

**Comment by CJY0208** [comment]
> @harryyuanfeng
> 我也是这个问题，加了行代码后解决了
> https://github.com/sakuyamaij/sms-boom/commit/79e2de8449fe1b079ccf63dc7c8cee7f9b53abc9

@sakuyamaij 你好，我遇到了同样的问题，但附带的链接打不开了，请问是怎样解决的呀？
