### ISSUE TITLE
node index.js报错，请问需要修改哪里？

### ISSUE THREAD

**Issue by iWynn** [axetroy/sms-boom#5]
Error: Evaluation failed: DOMException: Failed to execute 'querySelector' on 'Document': '13800000000' is not a valid selector.
    at selector (<anonymous>:1:23)
    at ExecutionContext.evaluateHandle (C:\Users\Administrator\node_modules\puppeteer\lib\ExecutionContext.js:66:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: Cannot read property 'type' of null
    at Page.type (C:\Users\Administrator\node_modules\puppeteer\lib\Page.js:798:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by axetroy** [comment]
@iWynn 
首先设置环境变量process.env.PHONE=电话号码，否则默认是13800000000

**Comment by axetroy** [comment]
@iWynn 
已经更新README，里面有使用指南

**Comment by iWynn** [comment]
感谢
