### ISSUE TITLE
运行报错 Centos7 node-v11 

### ISSUE THREAD

**Issue by Jrexexe** [axetroy/sms-boom#58]
``` 
[21561]: start.
TypeError: input.on is not a function
    at new Interface (readline.js:199:11)
    at Object.createInterface (readline.js:69:10)
    at Promise (/usr/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:196:25)
    at new Promise (<anonymous>)
    at waitForWSEndpoint (/usr/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:195:10)
    at Function.launch (/usr/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Launcher.js:133:39)
Error caught in uncaughtException event: { Error: spawn /usr/lib/node_modules/smsboomer/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:19)
    at onErrorNT (internal/child_process.js:413:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  errno: 'EACCES',
  code: 'EACCES',
  syscall:
   'spawn /usr/lib/node_modules/smsboomer/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome',
  path:
   '/usr/lib/node_modules/smsboomer/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome',
  spawnargs:
   [ '--disable-background-networking',
     '--disable-background-timer-throttling',
     '--disable-client-side-phishing-detection',
     '--disable-default-apps',
     '--disable-extensions',
     '--disable-hang-monitor',
     '--disable-popup-blocking',
     '--disable-prompt-on-repost',
     '--disable-sync',
     '--disable-translate',
     '--metrics-recording-only',
     '--no-first-run',
     '--remote-debugging-port=0',
     '--safebrowsing-disable-auto-update',
     '--enable-automation',
     '--password-store=basic',
     '--use-mock-keychain',
     '--user-data-dir=/tmp/puppeteer_dev_profile-1fdreR',
     '--headless',
     '--disable-gpu',
     '--hide-scrollbars',
     '--mute-audio' ] }
[21561]: Exit with code 0.
```

之前遇到的headless问题也解决了，不能用root用户运行 chrome 也解决了，一运行又出错，麻烦指引一下

**Comment by huadaonan** [comment]
同样的问题
